### ISSUE TITLE
Display additonal system traits?

### ISSUE THREAD

**Issue by PhilRoi** [daveah/ti4_planet_selection#14]
While you do not want to introduce tech skips and planet types as constraints,  would you consider adding these traits to the displayed output?

**Comment by daveah** [comment]
I can definitely do this.  I'll see about doing an interim release in the near future that adds this prior to the PoK release later in the year.

**Comment by PhilRoi** [comment]
thanks, looking to use the tool to help out with our charity world tournament! it'll be sweet for that!

**Comment by daveah** [comment]
I'm working on a change to print the tech skips and planet traits out.  A quick question - are you using this from the website, or with the python script in github?
I've got a working python version I can check in now; but the website will take me a few more days - problems with the javascript compiler right now.

**Comment by daveah** [comment]
Ok, I managed to finish the refactor for planet traits and tech so it now works with the javascript compiler.  Code here and website have both been updated.
Let me know if that works for you.
