### ISSUE TITLE
Ba'kal data seems wrong

### ISSUE THREAD

**Issue by matkoniecz** [daveah/ti4_planet_selection#16]
https://github.com/daveah/ti4_planet_selection/blob/master/_tiles.py#L60

**Comment by daveah** [comment]
Looks that way.  I'll take a detailed look tomorrow and publish a fix

**Comment by daveah** [comment]
Should be fixed in master and published to the website now.

**Comment by matkoniecz** [comment]
https://github.com/daveah/ti4_planet_selection/commit/ef1b124eafead747fe9d6122aaf76e59d959b479
